//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class SigmaCreationPersoContainer : DbContext
{
    public SigmaCreationPersoContainer()
        : base("name=SigmaCreationPersoContainer")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Joueur> Joueurs { get; set; }
    public virtual DbSet<Personnage> Personnages { get; set; }
    public virtual DbSet<Attribut> Attributs { get; set; }
    public virtual DbSet<EquipementEmporte> EquipementEmportes { get; set; }
    public virtual DbSet<SpecialitesSecondaire> SpecialitesSecondaires { get; set; }
    public virtual DbSet<UnitesSpeciale> UnitesSpeciales { get; set; }
    public virtual DbSet<UnitesSpecialesLangage> UnitesSpecialesLangages { get; set; }
    public virtual DbSet<Langage> Langages { get; set; }
    public virtual DbSet<ArmesEmportee> ArmesEmportees { get; set; }
    public virtual DbSet<Arme> Armes { get; set; }
    public virtual DbSet<ArmesMotsCle> ArmesMotsCles { get; set; }
    public virtual DbSet<MotsCle> MotsCles { get; set; }
    public virtual DbSet<ArmesType> ArmesTypes { get; set; }
    public virtual DbSet<ClassesSoldat> ClassesSoldats { get; set; }
    public virtual DbSet<ClassesArmesType> ClassesArmesTypes { get; set; }
    public virtual DbSet<SpecialitesPrimaire> SpecialitesPrimaires { get; set; }
    public virtual DbSet<ManoeuvresTactique> ManoeuvresTactiques { get; set; }
    public virtual DbSet<BonusAttribut> BonusAttributs { get; set; }
    public virtual DbSet<Equipement> Equipements { get; set; }
    public virtual DbSet<EquipementSpecialite> EquipementSpecialites { get; set; }
    public virtual DbSet<Armure> Armures { get; set; }
    public virtual DbSet<SpecialitesPrimairesBonu> SpecialitesPrimairesBonus { get; set; }
}
