//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Arme
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Arme()
    {
        this.ArmesEmportees = new HashSet<ArmesEmportee>();
        this.ArmesMotsCles = new HashSet<ArmesMotsCle>();
    }

    public int Id { get; set; }
    public string nom { get; set; }
    public string distanceCourte { get; set; }
    public string distanceLongue { get; set; }
    public string dommage { get; set; }
    public string teteAtteinte { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ArmesEmportee> ArmesEmportees { get; set; }
    public virtual UnitesSpeciale UnitesSpeciale { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ArmesMotsCle> ArmesMotsCles { get; set; }
    public virtual ArmesType ArmesType { get; set; }
}

public partial class ArmesEmportee
{
    public int Id { get; set; }

    public virtual Personnage Personnage { get; set; }
    public virtual Arme Arme { get; set; }
}

public partial class ArmesMotsCle
{
    public int Id { get; set; }

    public virtual Arme Arme { get; set; }
    public virtual MotsCle MotsCle { get; set; }
}

public partial class ArmesType
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ArmesType()
    {
        this.Armes = new HashSet<Arme>();
        this.ClassesArmesTypes = new HashSet<ClassesArmesType>();
    }

    public int Id { get; set; }
    public string nom { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Arme> Armes { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ClassesArmesType> ClassesArmesTypes { get; set; }
}

public partial class Armure
{
    public int Id { get; set; }
    public string modele { get; set; }
    public int bonus { get; set; }
    public int absortion { get; set; }
    public int vitesse { get; set; }

    public virtual Equipement Equipement { get; set; }
}

public partial class Attribut
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Attribut()
    {
        this.Personnages = new HashSet<Personnage>();
    }

    public int Id { get; set; }
    public string type { get; set; }
    public int combat { get; set; }
    public int tir { get; set; }
    public int eveil { get; set; }
    public int furtivite { get; set; }
    public int resistence { get; set; }
    public int leadership { get; set; }
    public int formePhysique { get; set; }
    public int capaciteTechnique { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Personnage> Personnages { get; set; }
}

public partial class BonusAttribut
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BonusAttribut()
    {
        this.SpecialitesPrimairesBonus = new HashSet<SpecialitesPrimairesBonu>();
    }

    public int Id { get; set; }
    public string bonusAttribut { get; set; }
    public int valeur { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SpecialitesPrimairesBonu> SpecialitesPrimairesBonus { get; set; }
}

public partial class ClassesArmesType
{
    public int Id { get; set; }

    public virtual ClassesSoldat ClassesSoldat { get; set; }
    public virtual ArmesType ArmesType { get; set; }
}

public partial class ClassesSoldat
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ClassesSoldat()
    {
        this.Personnages = new HashSet<Personnage>();
        this.ClassesArmesTypes = new HashSet<ClassesArmesType>();
    }

    public int Id { get; set; }
    public string nom { get; set; }
    public string bonus { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Personnage> Personnages { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ClassesArmesType> ClassesArmesTypes { get; set; }
}

public partial class Equipement
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Equipement()
    {
        this.EquipementEmportes = new HashSet<EquipementEmporte>();
        this.EquipementSpecialites = new HashSet<EquipementSpecialite>();
        this.Armures = new HashSet<Armure>();
    }

    public int Id { get; set; }
    public string nom { get; set; }
    public string nonEntraine { get; set; }
    public string entraine { get; set; }
    public int Armures_Id { get; set; }
    public string Type { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EquipementEmporte> EquipementEmportes { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EquipementSpecialite> EquipementSpecialites { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Armure> Armures { get; set; }
}

public partial class EquipementEmporte
{
    public int Id { get; set; }
    public string nom { get; set; }
    public bool entraine { get; set; }

    public virtual Personnage Personnage { get; set; }
    public virtual Equipement Equipement { get; set; }
}

public partial class EquipementSpecialite
{
    public int Id { get; set; }

    public virtual Equipement Equipement { get; set; }
    public virtual SpecialitesSecondaire SpecialitesSecondaire { get; set; }
}

public partial class Joueur
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Joueur()
    {
        this.Personnages = new HashSet<Personnage>();
    }

    public int Id { get; set; }
    public string prenom { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Personnage> Personnages { get; set; }
}

public partial class Langage
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Langage()
    {
        this.UnitesSpecialesLangages = new HashSet<UnitesSpecialesLangage>();
    }

    public int Id { get; set; }
    public string nom { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UnitesSpecialesLangage> UnitesSpecialesLangages { get; set; }
}

public partial class ManoeuvresTactique
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ManoeuvresTactique()
    {
        this.SpecialitesPrimaires = new HashSet<SpecialitesPrimaire>();
    }

    public int Id { get; set; }
    public string nom { get; set; }
    public string description { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SpecialitesPrimaire> SpecialitesPrimaires { get; set; }
}

public partial class MotsCle
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MotsCle()
    {
        this.ArmesMotsCles = new HashSet<ArmesMotsCle>();
    }

    public int Id { get; set; }
    public string nom { get; set; }
    public string effet { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ArmesMotsCle> ArmesMotsCles { get; set; }
}

public partial class Personnage
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Personnage()
    {
        this.EquipementEmportes = new HashSet<EquipementEmporte>();
        this.ArmesEmportees = new HashSet<ArmesEmportee>();
    }

    public int Id { get; set; }
    public string prenom { get; set; }
    public string nom { get; set; }
    public string nomDeCode { get; set; }
    public int niveau { get; set; }
    public string descriptionPhsique { get; set; }
    public string biographie { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EquipementEmporte> EquipementEmportes { get; set; }
    public virtual SpecialitesSecondaire SpecialitesSecondaire { get; set; }
    public virtual UnitesSpeciale UnitesSpeciales { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ArmesEmportee> ArmesEmportees { get; set; }
    public virtual ClassesSoldat ClassesSoldat { get; set; }
    public virtual SpecialitesPrimaire SpecialitesPrimaire { get; set; }
    public virtual Joueur Joueur { get; set; }
    public virtual Attribut Attribut { get; set; }
}

public partial class SpecialitesPrimaire
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SpecialitesPrimaire()
    {
        this.Personnages = new HashSet<Personnage>();
        this.SpecialitesPrimairesBonus = new HashSet<SpecialitesPrimairesBonu>();
    }

    public int Id { get; set; }
    public string nom { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Personnage> Personnages { get; set; }
    public virtual ManoeuvresTactique ManoeuvresTactique { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SpecialitesPrimairesBonu> SpecialitesPrimairesBonus { get; set; }
}

public partial class SpecialitesPrimairesBonu
{
    public int Id { get; set; }

    public virtual BonusAttribut BonusAttribut { get; set; }
    public virtual SpecialitesPrimaire SpecialitesPrimaire { get; set; }
}

public partial class SpecialitesSecondaire
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SpecialitesSecondaire()
    {
        this.Personnages = new HashSet<Personnage>();
        this.EquipementSpecialites = new HashSet<EquipementSpecialite>();
    }

    public int Id { get; set; }
    public string nom { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Personnage> Personnages { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EquipementSpecialite> EquipementSpecialites { get; set; }
}

public partial class UnitesSpeciale
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UnitesSpeciale()
    {
        this.Personnage = new HashSet<Personnage>();
        this.UnitesSpecialesLangages = new HashSet<UnitesSpecialesLangage>();
        this.Armes = new HashSet<Arme>();
    }

    public int Id { get; set; }
    public string nom { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Personnage> Personnage { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UnitesSpecialesLangage> UnitesSpecialesLangages { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Arme> Armes { get; set; }
}

public partial class UnitesSpecialesLangage
{
    public int Id { get; set; }

    public virtual UnitesSpeciale UnitesSpeciale { get; set; }
    public virtual Langage Langage { get; set; }
}
